### ISSUE TITLE
metrics: add process filter in metrics detail page

### ISSUE THREAD

**Issue by andrewsmedina** [tsuru/tsuru-dashboard#107]
the metrics list in "resources" page has a filter by process (web, worker). the metrics details page should has the same filter.

**Comment by andrestc** [comment]
@andrewsmedina I was thinking about closing this issue since we removed the metrics detail page. But it might be a cool idea to have this kind of filtering on the pool metrics, to filter metrics on only some of pool's host). What do you think?
