### ISSUE TITLE
Get tsuru token failed in Login.form_valid()

### ISSUE THREAD

**Issue by smartwang** [tsuru/tsuru-dashboard#117]
I encountered an error  while login.

I changed the code in Login.form_valid() to solve this problem:

`
    response = requests.post(url, data=data)
`
Maybe it's a bug

**Comment by andrewsmedina** [comment]
Hi @smartwang, the `tsuru-dashboard` from master does not work fine with tsurud from master.

But there is a branch 1.0 that works fine with tsurud master version and this bug is already fixed: https://github.com/tsuru/tsuru-dashboard/blob/tsuru1.0/tsuru_dashboard/auth/views.py#L133

**Comment by smartwang** [comment]
Aha,the answer to my question, thanks a lot:-)
