### ISSUE TITLE
Admin/Nodes page always use Brazilian timezone

### ISSUE THREAD

**Issue by fsouza** [tsuru/tsuru-dashboard#129]
<img width="1277" alt="image" src="https://cloud.githubusercontent.com/assets/108725/19950038/8af13706-a12b-11e6-9eae-b0d4448d7acf.png">

We should either use UTC or the local timezone (like we do in the command line).

**Comment by filipposc5** [comment]
I 've noticed that editing abyss/settings.py and setting TIME_ZONE=UTC will change this view.

**Comment by fsouza** [comment]
Nice catch @filipposc5, I added a new environment variable for that. The default value is still ``America/Sao_Paulo``, so we don't break existing installations.
