### ISSUE TITLE
bug: Rebalance not correctly sending metadata filters

### ISSUE THREAD

**Issue by andrestc** [tsuru/tsuru-dashboard#142]
A [bug in tsuru python client](https://github.com/tsuru/python-tsuruclient/issues/9) is causing the node rebalance metadatafilter (e.g pool) to be ignored by tsuru api. We should update python-tsuruclient as soon as it is fixed.

**Comment by ggarnier** [comment]
Closed via c33fcd29bf0ba10f9e3698b472ca4b4dd898d9df
