### ISSUE TITLE
Dashboard does not remember my session

### ISSUE THREAD

**Issue by siminm** [tsuru/tsuru-dashboard#85]
After the dashboard is up and running, I can login successfully and see the /apps contents. Clicking any link sends me back to /auth/login.

Style files such as /static/css/bootstrap.min.css also redirect me to /auth/login

**Comment by andrewsmedina** [comment]
fixed by https://github.com/tsuru/tsuru-dashboard/commit/00a1590b8d770913ded6f4395b0d8b35de1a79a2
