### ISSUE TITLE
deploys: clicking on a deploy ran with app-deploy fails

### ISSUE THREAD

**Issue by fsouza** [tsuru/tsuru-dashboard#87]
When user uses ``app-deploy`` to send the code to production, it's impossible to see the details of the deployment in the dashboard.

Not sure if we can show many things, but currently it simply doesn't work.

**Comment by andrewsmedina** [comment]
@fsouza after tsr 0.10.0 this page can show the deploy log output.

**Comment by andrewsmedina** [comment]
blocked by https://github.com/tsuru/tsuru/issues/1098

**Comment by andrewsmedina** [comment]
fixed by https://github.com/tsuru/tsuru-dashboard/commit/0c9a178dcfd81a932314907ce2b1b5f21197c47f
